name: flutter_wallpaper_application
description: A new Flutter project.
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.4
  equatable: ^2.0.5
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  fluttertoast: ^8.2.2
  http: ^1.1.0
  image_gallery_saver: ^2.0.3
  font_awesome_flutter: ^10.5.0
  flutter_wallpaper_manager: ^0.0.4
  lazy_load_scrollview: ^1.3.0
  path_provider: ^2.0.15
  shimmer: ^3.0.0
  upgrader: ^8.1.0
  flutter_staggered_grid_view: ^0.7.0
  hexcolor: ^3.0.1
  google_sign_in: ^6.1.4
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.7
  firebase_app_check: ^0.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/onboarding/